name: auto-changelog

on:
  pull_request:
    branches: [develop]
    types: [opened, edited]
  pull_request_review:
    types: [submitted]  

  issue_comment:
    types: [edited]

jobs:
  changelog:
    if: ${{ github.event.pull_request}}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - uses: TDesignOteam/flow-pilot-action@develop
        id: changelog
        with:
          token: ${{ secrets.PERSONAL_TOKEN }}
          packages: 'pkg-a,pkg-b,pkg-c'
      
      - run: echo "${{ steps.changelog.outputs.changelog }}" > changelog.md
      
      - uses: actions/upload-artifact@v4
        with:
          name: changelog
          path: changelog.md
          retention-days: 5

      - run: echo ${{ github.event.number }} > pr-id.txt

      - uses: actions/upload-artifact@v4
        with:
          name: pr-id
          path: pr-id.txt
          retention-days: 5    

  commit-changelog:
    if: github.event.issue.pull_request
    runs-on: ubuntu-latest
    steps:
      - name: auto-changelog
        uses: TDesignOteam/flow-pilot-action@develop
        with:
          token: ${{ secrets.PERSONAL_TOKEN }}
          packages: 'pkg-a,pkg-b,pkg-c'
