name: Auto_Publish

on:
  pull_request_target:
    branches: [main]
    types: [close]
jobs:
  publish:
    if: github.event.pull_request.merged && startsWith(github.head_ref, 'release/')
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - uses: pnpm/action-setup@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 18    

      - uses: TDesignOteam/flow-pilot-action@develop
        with:
          token: ${{ secrets.PERSONAL_TOKEN }}
          packages: "pkg-a,pkg-b,pkg-c"