name: auto-changelog-callback

on:
  workflow_run:
    workflows:
      - auto-changelog
    types:
      - completed

jobs:
  comment:
    if: ${{ github.event.workflow_run.conclusion == 'success'}}
    runs-on: ubuntu-latest
    steps:
      - uses: TDesignOteam/flow-pilot-action@develop
        with:
          token: ${{ secrets.PERSONAL_TOKEN }}
          packages: 'pkg-a,pkg-b,pkg-c'