name: flow-pilot

on:
  pull_request:
    branches: [main]
    types: [opened,synchronize, edited,closed]
  issue_comment:
    types: [edited]  

jobs:
  flow:
    runs-on: ubuntu-latest
    steps:
      - uses: TDesignOteam/flow-pilot-action@develop
        with:
          token: ${{ secrets.PERSONAL_TOKEN }}
          packages: "pkg-a,pkg-b,pkg-c"
