name: flow-pilot

on:
  pull_request:
    branches: [main]

jobs:
  flow:
    runs-on: ubuntu-latest
    steps:
      - uses: TDesignOteam/flow-pilot-action@develop
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
