# 当打上 "Need Reproduce" 标签时，自动提示提供重现实例
name: Issue Need Reproduce

on:
  issues:
    types: [labeled]

jobs:
  call-issue-welcome:
    uses: TDesignOteam/workflows/.github/workflows/reusable-issue-need-reproduce.yml@reusable-issue
