# 当打上 easy/middle/hard 标签时，追加难度分级模板
name: Issue Shoot

on:
  issues:
    types: ["labeled"]

jobs:
  call-issue-welcome:
    uses: TDesignOteam/workflows/.github/workflows/reusable-issue-shoot.yml@reusable-issue
