# 当 issue 被创建时，自动回复引导完善信息
name: Issue Welcome

on:
  issues:
    types: [opened]

jobs:
  call-issue-welcome:
    uses: TDesignOteam/workflows/.github/workflows/reusable-issue-welcome.yml@reusable-issue
    with:
      issue-number: ${{ github.event.issue.number }}
      login: ${{ github.event.issue.user.login }}
      token: ${{ secrets.GITHUB_TOKEN }}
